"""
ICC-based Feature Selector

This module provides a feature selector that filters features based on their
Intraclass Correlation Coefficient (ICC) values.
"""
import json
from typing import Dict, List
from .selector_registry import register_selector

@register_selector('icc')
def icc_selector(
    icc_results_path: str, 
    groups: List[str], 
    threshold: float = 0.75
) -> List[str]:
    """
    Filters features by selecting those that meet a minimum ICC threshold
    across a specified set of groups.

    This function reads a JSON file of ICC results generated by the main `icc`
    command, selects features that are above the threshold in all specified
    groups, and returns a list of the common selected features.

    Args:
        icc_results_path (str): Path to the JSON file containing ICC results.
        groups (List[str]): A list of group names (e.g., 'rater1_vs_rater2')
                              from the ICC results to use for selection.
        threshold (float): The minimum ICC value for a feature to be considered
                           stable. Defaults to 0.75.

    Returns:
        List[str]: A list of feature names that meet the ICC threshold in
                   all specified groups.
    """
    try:
        with open(icc_results_path, 'r') as f:
            icc_results = json.load(f)
    except FileNotFoundError:
        raise FileNotFoundError(f"ICC results file not found at: {icc_results_path}")
    except json.JSONDecodeError:
        raise ValueError(f"Could not decode JSON from file: {icc_results_path}")

    if not groups:
        raise ValueError("The 'groups' list cannot be empty.")

    selected_features_per_group = []

    for group_name in groups:
        if group_name not in icc_results:
            raise KeyError(f"Group '{group_name}' not found in the ICC results file.")
        
        features_in_group = icc_results[group_name]
        
        # Find the primary ICC value to use for thresholding (e.g., 'ICC3', 'ICC2')
        # This logic assumes the result dictionary for each feature holds metric dicts.
        stable_features = set()
        for feature, metrics in features_in_group.items():
            if not isinstance(metrics, dict):
                continue

            # Find a suitable ICC value to use for thresholding
            icc_value = None
            # Prioritize common ICC types
            for key in ['ICC3', 'ICC2', 'icc3', 'icc2']:
                if key in metrics and isinstance(metrics[key], dict):
                    icc_value = metrics[key].get('value')
                    break
            
            # If no prioritized ICC is found, take the first available ICC value
            if icc_value is None:
                for key, result in metrics.items():
                     if 'icc' in key.lower() and isinstance(result, dict) and 'value' in result:
                         icc_value = result.get('value')
                         break

            if icc_value is not None and icc_value >= threshold:
                stable_features.add(feature)
        
        selected_features_per_group.append(stable_features)

    # Find the intersection of stable features across all specified groups
    if not selected_features_per_group:
        return []
        
    common_stable_features = set.intersection(*selected_features_per_group)
    
    return sorted(list(common_stable_features))
