# 生境分析的参数配置

# 数据路径
data_dir: F:\\work\\workstation_b\\dingHuYingXiang\\the_third_training_202504\\demo_data\\datasets
out_dir: F:\\work\\workstation_b\\dingHuYingXiang\\the_third_training_202504\\demo_data\\results

# Preprocessing
Preprocessing:
  N4BiasCorrection:
    enabled: true
    images: [pre_contrast, LAP, PVP, delay_3min]

  resample:
    images: [pre_contrast, LAP, PVP, delay_3min]

  registration:
    images: [pre_contrast, LAP, PVP, delay_3min]
    fixedImage: PVP
    movingImage: [pre_contrast, LAP, delay_3min]

# 特征构建中的method是必选参数，后面的参数根据用自定义的特征构建方法来填写
# 比如KineticFeatureExtractor类需要timestamps参数，则后面必须设置
# 特征构建的输入中数据是df格式, header 是images的名字，即subj 文件夹下面的图像文件夹的名字
# 如果是其它参数，则相应修改
  # 时间序列特征. 如果method是kinetic，则必须设置
  # 时间序列特征文件是excel或者csv文件，第一列是subjID,后面是每个图像的扫描时间
  # 时间戳文件格式说明：
  # 1. 支持CSV或Excel格式
  # 2. 第一列必须是患者ID（与文件夹名称匹配）
  # 3. 后续列必须与输入图像名称匹配
  # 比如输入是pre_contrast, LAP, PVP, delay_3min，则时间序列特征文件的header必须有pre_contrast, LAP, PVP, delay_3min
  # 
  # 示例CSV格式：
  # | subjID                         | pre_contrast| LAP    | PVP    | delay_3min |
  # |--------------------------------|-------------|---------|---------|------------|
  # | patient001                     | 10:15:30    | 10:16:45| 10:18:20| 10:21:30   |
  # | patient002                     | 14:20:10    | 14:21:25| 14:23:00| 14:26:15   |
  # 注意：时间格式应为HH-MM-SS或HH:MM:SS
FeatureConstruction:
  image_names: [pre_contrast, LAP, PVP, delay_3min]
  method: kinetic  # 可选: kinetic, simple, 持续更新
  timestamps: F:\\work\\research\\radiomics_TLSs\\data\\scan_time_of_phases.xlsx
  # timestamps的subjID必须与data_dir中的subjID一致

HabitatsSegmention:
  method: 2step  # 目前只支持二步聚类法
  supervoxel:
    algorithm: kmeans
    n_clusters: 50
  
  habitat:
    algorithm: kmeans
    max_clusters: 10
    habitat_cluster_selection_method: inertia
    best_n_clusters: 
    
# 其他参数
processes: 4
plot_curves: true
random_state: 42 