data_dir: /mnt/f/work/habit_project_v1/demo_data/preprocessed/processed_images
out_dir: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/preprocess_n4_resample_registration/outputs
auto_select_first_file: true
Preprocessing:
  n4_correction:
    images:
    - T1
    - T2
    num_fitting_levels: 2
  resample:
    images:
    - T1
    - T2
    target_spacing:
    - 2.0
    - 2.0
    - 2.0
  registration:
    images:
    - T1
    - T2
    fixed_image: T1
    use_mask: true
    backend: elastix
    elastix_parameter_files: /mnt/f/work/habit_project_v1/demo_data/Par0040affine.txt
save_options:
  save_intermediate: true
  intermediate_steps:
  - n4_correction
  - resample
  - registration
processes: 1
random_state: 42
