
import base64
exec(base64.b64decode(b'IiIiDQpDb3JlIG1vZHVsZXMgZm9yIEhBQklUIHBhY2thZ2UuDQoiIiINCg0KZnJvbSAuaGFiaXRhdF9hbmFseXNpcyBpbXBvcnQgSGFiaXRhdEFuYWx5c2lzLCBIYWJpdGF0RmVhdHVyZUV4dHJhY3Rvcg0KZnJvbSAubWFjaGluZV9sZWFybmluZyBpbXBvcnQgTW9kZWxpbmcNCg0KX19hbGxfXyA9IFsiSGFiaXRhdEFuYWx5c2lzIiwgIkhhYml0YXRGZWF0dXJlRXh0cmFjdG9yIiwgIk1vZGVsaW5nIl0g').decode())
