#!/usr/bin/env bash
# One-time setup for conda-pack HABIT (macOS / Linux).
# Place at pack root (same folder as bin/python), then run:
#   bash setup_habit.sh
#
# Steps: conda-unpack (once, silent) + prepend pack bin/ to shell PATH (front).

set -euo pipefail

EXIT_CODE=0

resolve_pack_root() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if [[ -f "${script_dir}/bin/python" || -x "${script_dir}/bin/python" ]]; then
        echo "${script_dir}"
        return
    fi
    if [[ -f "${PWD}/bin/python" || -x "${PWD}/bin/python" ]]; then
        echo "${PWD}"
        return
    fi
    echo ""
}

PACK_ROOT="$(resolve_pack_root)"
BIN="${PACK_ROOT}/bin"
HABIT_BIN="${BIN}/habit"
CONDA_UNPACK="${BIN}/conda-unpack"
UNPACK_MARKER="${PACK_ROOT}/.habit_unpacked"
SETUP_LOG="${PACK_ROOT}/.habit_setup.log"
PATH_SNIPPET="${PACK_ROOT}/.habit_path.sh"

if [[ -z "${PACK_ROOT}" ]]; then
    echo
    echo "[HABIT] ERROR: Cannot find conda-pack root (bin/python)."
    echo "Run this script from the extracted pack root, not from developer/ in the repo."
    EXIT_CODE=1
    exit "${EXIT_CODE}"
fi

echo
echo "=== HABIT one-time setup (Unix) ==="
echo "Pack root: ${PACK_ROOT}"
echo

if [[ ! -x "${HABIT_BIN}" && ! -f "${HABIT_BIN}" ]]; then
    echo "[HABIT] ERROR: habit not found: ${HABIT_BIN}" >&2
    exit 1
fi

# --- conda-unpack ---
if [[ -f "${UNPACK_MARKER}" ]]; then
    echo "[1/2] Environment paths already configured; skipping."
elif [[ -x "${CONDA_UNPACK}" || -f "${CONDA_UNPACK}" ]]; then
    echo "[1/2] Configuring environment paths ..."
    set +e
    (cd "${PACK_ROOT}" && "${CONDA_UNPACK}" >"${SETUP_LOG}" 2>&1)
    UNPACK_ERR=$?
    set -e
    if [[ ${UNPACK_ERR} -eq 0 ]]; then
        echo "      Done."
        echo "done" >"${UNPACK_MARKER}"
    elif "${HABIT_BIN}" --version >/dev/null 2>&1; then
        echo "      Done (verified)."
        echo "verified" >"${UNPACK_MARKER}"
    else
        echo "[HABIT] ERROR: Environment setup failed. See ${SETUP_LOG}" >&2
        exit 1
    fi
else
    echo "[1/2] conda-unpack not found; skipping."
    "${HABIT_BIN}" --version >/dev/null 2>&1 || {
        echo "[HABIT] ERROR: habit cannot run." >&2
        exit 1
    }
fi

# --- PATH snippet (source from ~/.bashrc / ~/.zshrc) ---
echo "[2/2] Writing PATH snippet ..."

cat >"${PATH_SNIPPET}" <<EOF
# HABIT portable pack (generated by setup_habit.sh)
export PATH="${BIN}:${PACK_ROOT}:\${PATH}"
EOF
chmod +x "${PATH_SNIPPET}" 2>/dev/null || true

SOURCE_LINE="source \"${PATH_SNIPPET}\""

update_shell_rc() {
    local rc_file="$1"
    if [[ ! -f "${rc_file}" ]]; then
        return 1
    fi
    if grep -Fq "${PATH_SNIPPET}" "${rc_file}" 2>/dev/null; then
        echo "      Already in ${rc_file}"
        return 0
    fi
    {
        echo ""
        echo "# HABIT portable pack"
        echo "${SOURCE_LINE}"
    } >>"${rc_file}"
    echo "      Appended to ${rc_file}"
    return 0
}

UPDATED=0
if update_shell_rc "${HOME}/.bashrc"; then UPDATED=1; fi
if update_shell_rc "${HOME}/.zshrc"; then UPDATED=1; fi

if [[ ${UPDATED} -eq 0 ]]; then
    echo "      Add this line to your shell rc file:"
    echo "      ${SOURCE_LINE}"
fi

# --- verify ---
"${HABIT_BIN}" --version >/dev/null 2>&1 || {
    echo "[HABIT] ERROR: habit failed after setup." >&2
    exit 1
}

echo
echo "Setup complete."
echo
echo "Open a NEW terminal, or run:"
echo "  source \"${PATH_SNIPPET}\""
echo "Then verify:"
echo "  which habit"
echo "  habit --version"
echo
echo "Optional GPU torch upgrade (NVIDIA GPU on Linux only):"
echo "  bash install_gpu_torch.sh"
