input:
- path: /mnt/f/work/habit_project_v1/demo_data/ml_data/breast_cancer_dataset.csv
  name: radiomics_
  subject_id_col: subjID
  label_col: label
  features: null
output: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/ml_kfold/outputs
n_splits: 5
stratified: true
random_state: 42
normalization:
  method: z_score
resampling:
  enabled: false
  method: random_over
  position: before_model
  ratio: 1.0
  random_state: 42
feature_selection_methods:
- method: correlation
  params:
    threshold: 0.8
    method: spearman
    visualize: false
    before_z_score: false
- method: variance
  params:
    before_z_score: true
    top_k: 20
    plot_variances: true
is_visualize: true
is_save_model: true
models:
  LogisticRegression:
    params:
      random_state: 42
      max_iter: 1000
      C: 1.0
      penalty: l2
      solver: lbfgs
  RandomForest:
    params:
      random_state: 42
      n_estimators: 100
      max_depth: null
      max_features: sqrt
  XGBoost:
    params:
      random_state: 42
      n_estimators: 100
      max_depth: 3
      learning_rate: 0.1
visualization:
  enabled: true
  plot_types:
  - roc
  - calibration
  - confusion
  - dca
