# Configuration file for habitat feature extraction

# Parameter files
params_file_of_non_habitat: ./config/parameter.yaml  # Parameter file for extracting radiomics features from original images
params_file_of_habitat: ./config/parameter_habitat.yaml  # Parameter file for extracting radiomics features from habitat maps

# Data directories
raw_img_folder: H:\Registration_ZSSY_1mm_structured  # Root directory containing original images
habitats_map_folder: H:\results  # Root directory containing habitat maps
out_dir: H:\results  # Output directory for results

# Feature extraction parameters
n_processes: 3  # Number of processes to use for parallel processing
habitat_pattern: '*_habitats.nrrd'  # Pattern for matching habitat files

# Feature type parameters
feature_types:  # Types of features to extract
  - traditional
  - non_radiomics
  - whole_habitat
  # - each_habitat
  - msi
  - ith_score


n_habitats:   # Number of habitats to process (empty for auto detection)

# Debug parameter
debug: false  # Enable debug mode 