# Habitat Analysis Configuration

# Data paths
data_dir: F:\work\research\radiomics_TLSs\data\results_420\processed_images
out_dir: F:\\work\\research\\radiomics_TLSs\\data\\results_420

# Feature extraction settings
FeatureConstruction:
  voxel_level:
    method: concat(raw(pre_contrast), raw(LAP), raw(PVP), raw(delay_3min))
    params:
      params_file: ./config/params_voxel_radiomics.yaml
      kernelRadius: 3  # if voxel_radiomics is used, you can set another kernelRadius value

  supervoxel_level:
    supervoxel_file_keyword: '*_supervoxel.nrrd'
    method: mean_voxel_features()  
    params:
      params_file: ./config/params_supervoxel_radiomics.yaml

  preprocessing:  # Current only for voxel_level features, and populating the missing values with the mean of the feature
    methods:
      - method: winsorize
        winsor_limits: [0.05, 0.05]
        global_normalize: true
      - method: minmax
        global_normalize: true

# Habitat segmentation settings
HabitatsSegmention:
  # Supervoxel clustering settings
  supervoxel:
    algorithm: kmeans
    n_clusters: 50
    random_state: 42
    max_iter: 300
    n_init: 10
  
  # Habitat clustering settings
  habitat:
    algorithm: kmeans
    max_clusters: 10
    habitat_cluster_selection_method: inertia  # inertia, silhouette, or calinski_harabasz
    best_n_clusters: null  # Set to null for automatic selection
    random_state: 42
    max_iter: 300
    n_init: 10

# General settings
processes: 2  # Number of parallel processes
plot_curves: true  # Whether to generate and save plots
random_state: 42  # Random seed for reproducibility
debug: false  # Enable debug mode for detailed logging 