# K-Fold Cross-Validation Machine Learning Configuration File
# This configuration file is specifically for k-fold cross-validation modeling

#%%================================================================================
# Data Input Configuration
input:
  - path: ./ml_data/breast_cancer_dataset.csv
    name: clinical_
    subject_id_col: subjID
    label_col: label
    features:

#%%================================================================================
# Output Directory Configuration
output: ./ml_data/kfold_results

#%%================================================================================
# K-Fold Cross-Validation Configuration
n_splits: 5  # Number of folds for cross-validation
stratified: true  # Whether to use stratified k-fold (preserves class distribution)
random_state: 42  # Random seed for reproducibility

#%%================================================================================
# Normalization Configuration
normalization:
  method: z_score  # Standardization method

#%%================================================================================
# Feature Selection Configuration
# Note: Feature selection is performed within each fold to avoid data leakage
feature_selection_methods:
  - method: correlation
    params:
      threshold: 0.80
      method: spearman
      visualize: false
      before_z_score: false

#%%================================================================================
# Visualization and Saving Configuration
is_visualize: true  # Whether to generate visualization plots (ROC, DCA, calibration curves, confusion matrices)
is_save_model: false  # Whether to save trained models from each fold (can be large)

#%%================================================================================
# Model Configuration
models:
  LogisticRegression:
    params:
      random_state: 42
      max_iter: 1000
      C: 1.0
      penalty: "l2"
      solver: "lbfgs"
  
  RandomForest:
    params:
      random_state: 42
      n_estimators: 100
      max_depth: null
      max_features: "sqrt"
  
  XGBoost:
    params:
      random_state: 42
      n_estimators: 100
      max_depth: 3
      learning_rate: 0.1

  # Add more models as needed
  # KNN:
  #   params:
  #     n_neighbors: 5
  #     weights: "uniform"
  
  # MLP:
  #   params:
  #     random_state: 42
  #     hidden_layer_sizes: [100, 50]
  #     max_iter: 200

#%%================================================================================  
# Visualization and Saving Configuration
is_visualize: true
is_save_model: true

visualization:
  enabled: true
  plot_types:
    - roc
    - calibration
    - confusion
    - dca