# Habitat Analysis Configuration

# Data paths
data_dir: H:\\Registration_ICC_structured_test
out_dir: F:\\work\\research\\radiomics_TLSs\\data\\results_420

# Preprocessing settings
Preprocessing:
  # N4_bias_correction:
  #   images: [pre_contrast, LAP, PVP, delay_3min]

  # resample:
  #   images: [pre_contrast, LAP, PVP, delay_3min]
  #   target_spacing: [1.0, 1.0, 1.0]  # Target voxel spacing in mm

  registration:
    images: [pre_contrast, LAP, PVP, delay_3min]
    fixed_image: PVP
    moving_images: [pre_contrast, LAP, delay_3min]
    type_of_transform: Rigid  # rigid or affine
    use_mask: false

# Feature extraction settings
FeatureConstruction:
  voxel_level:
    method: kinetic(raw(pre_contrast), raw(LAP), raw(PVP), raw(delay_3min), timestamps)
    params:
      params_voxel_radiomics: ./config/params_voxel_radiomics.yaml
      kernelRadius: 2
      timestamps: F:\\work\\research\\radiomics_TLSs\\data\\scan_time_of_phases.xlsx

  supervoxel_level:
    # TODO: method include mean_voxel_features, names using mean value of voxel features in each supervoxel
    supervoxel_file_keyword: '*_supervoxel.nrrd'
    # method: concat(supervoxel_radiomics(pre_contrast, params_file), supervoxel_radiomics(LAP, params_file), supervoxel_radiomics(PVP, params_file), supervoxel_radiomics(delay_3min, params_file))
    method: mean_voxel_features()
    params:
      params_file: ./config/parameter.yaml

  preprocessing:
    methods:
      - method: minmax
        global_normalize: true
      - method: winsorize
        winsor_limits: [0.05, 0.05]
        global_normalize: true

# Habitat segmentation settings
HabitatsSegmention:
  # Supervoxel clustering settings
  supervoxel:
    algorithm: kmeans
    n_clusters: 50
    random_state: 42
    max_iter: 300
    n_init: 10
  
  # Habitat clustering settings
  habitat:
    algorithm: kmeans
    max_clusters: 10
    habitat_cluster_selection_method: inertia  # inertia, silhouette, or calinski_harabasz
    best_n_clusters: null  # Set to null for automatic selection
    random_state: 42
    max_iter: 300
    n_init: 10

# General settings
processes: 2  # Number of parallel processes
plot_curves: true  # Whether to generate and save plots
random_state: 42  # Random seed for reproducibility
debug: false  # Enable debug mode for detailed logging 