# Configuration file for ICC analysis

# Input configuration
input:
  # Type of input: 'files' or 'directories'
  type: "files"
  
  # File groups configuration (used when type is 'files')
  # Each inner list represents a group of files to be analyzed together
  file_groups:
    # FIXME 切记：label列不能参与icc计算，如果参与了计算要从json中删除
    - [H:\results\features\ith_scores.csv, H:\results_icc_remapping\ith_scores.csv]
    - [H:\results\features\msi_features.csv, H:\results_icc_remapping\msi_features.csv]
    - [H:\results\features\whole_habitat_radiomics.csv, H:\results_icc_remapping\whole_habitat_radiomics.csv]
    - [H:\results\features\habitat_basic_features.csv, H:\results_icc_remapping\habitat_basic_features.csv]
    - [H:\results\features\raw_image_radiomics.csv, H:\results_icc_remapping\raw_image_radiomics.csv]
  
  # Directory list configuration (used when type is 'directories')
  # The system will match same-named files across directories
  # dir_list:
  #   - path/to/dir1
  #   - path/to/dir2
  #   - path/to/dir3

# Output configuration
output:
  # Path to output JSON file
  path: H:\results\icc_results_remapped.json

# Processing configuration
# Number of processes to use (null/None for using all available CPU cores)
processes: 6

# Debug mode (enables additional logging)
debug: false 