# Habitat Analysis Configuration

# Data paths
data_dir: H:\Registration_ICC_structured_test
out_dir: F:\\work\\research\\radiomics_TLSs\\data\\results_420

# Feature extraction settings
FeatureConstruction:
  voxel_level:
    method: kinetic(raw(pre_contrast), raw(LAP), raw(PVP), raw(delay_3min), timestamps)
    params:
      timestamps: F:\work\research\radiomics_TLSs\data\scan_time_of_phases.xlsx
      # params_file: ./config/params_voxel_radiomics.yaml
      # kernelRadius: 3  # if voxel_radiomics is used, you can set another kernelRadius value

  supervoxel_level:
    supervoxel_file_keyword: '*_supervoxel.nrrd'
    method: mean_voxel_features()  
    params:
      params_file: ./config/params_supervoxel_radiomics.yaml

  preprocessing:  # Current only for voxel_level features, and populating the missing values with the mean of the feature
    # methods:
      # - method: winsorize
      #   winsor_limits: [0.05, 0.05]
      #   global_normalize: true
      # - method: minmax
      #   global_normalize: true
      # - method: log
        # global_normalize: true

# Habitat segmentation settings
HabitatsSegmention:
  # Supervoxel clustering settings
  supervoxel:
    algorithm: kmeans
    n_clusters: 50
    random_state: 42
    max_iter: 300
    n_init: 10
  
  # Habitat clustering settings
  habitat:
    # training if you want to train a new model, testing if you want to use a pre-trained model, 
    # default feature preprocessing parameters are in os.path.join(self.out_dir, 'mean_values_of_all_supervoxels_features.csv')
    # default pre-trained model is os.path.join(self.out_dir, 'supervoxel2habitat_clustering_model.pkl')
    mode: training  # training or testing  
    algorithm: kmeans  # kmeans or gmm
    max_clusters: 10
    habitat_cluster_selection_method: inertia  # inertia, silhouette, or calinski_harabasz, aic or bic for gmm
    best_n_clusters: 4  # Set to null for automatic selection
    random_state: 42
    max_iter: 300
    n_init: 10

# General settings
processes: 3  # Number of parallel processes
plot_curves: true  # Whether to generate and save plots
random_state: 42  # Random seed for reproducibility
debug: false  # Enable debug mode for detailed logging 