# Habitat Analysis Configuration

# Data paths
data_dir: G:\\Registration_ICC_structured_test
out_dir: F:\\work\\research\\radiomics_TLSs\\data\\results_420

# Preprocessing settings
Preprocessing:
  N4BiasCorrection:
    enabled: true
    images: [pre_contrast, LAP, PVP, delay_3min]

  resample:
    images: [pre_contrast, LAP, PVP, delay_3min]
    target_spacing: [1.0, 1.0, 1.0]  # Target voxel spacing in mm

  registration:
    images: [pre_contrast, LAP, PVP, delay_3min]
    fixedImage: PVP
    movingImage: [pre_contrast, LAP, delay_3min]
    method: rigid  # rigid or affine

# Feature extraction settings
FeatureConstruction:
  image_names: [pre_contrast, LAP, PVP, delay_3min]
  method: kinetic  # kinetic, simple, or custom
  params:
    timestamps: F:\\work\\research\\radiomics_TLSs\\data\\scan_time_of_phases.xlsx
  preprocessing:
    methods:
      - method: minmax
        global_normalize: true
      - method: winsorize
        winsor_limits: [0.05, 0.05]
        global_normalize: true

# Habitat segmentation settings
HabitatsSegmention:
  method: 2step  # Two-step clustering method
  
  # Supervoxel clustering settings
  supervoxel:
    algorithm: kmeans
    n_clusters: 50
    random_state: 42
    max_iter: 300
    n_init: 10
  
  # Habitat clustering settings
  habitat:
    algorithm: kmeans
    max_clusters: 10
    habitat_cluster_selection_method: inertia  # inertia, silhouette, or calinski_harabasz
    best_n_clusters: null  # Set to null for automatic selection
    random_state: 42
    max_iter: 300
    n_init: 10

# General settings
processes: 4  # Number of parallel processes
plot_curves: true  # Whether to generate and save plots
random_state: 42  # Random seed for reproducibility
debug: false  # Enable debug mode for detailed logging 