# Habitat Analysis Configuration

# Data paths
data_dir: ./config/image_files.yaml
out_dir: ../demo_data/results/preprocessed

# 控制是否自动读取目录中的第一个文件
# true: 自动读取目录中的第一个文件 (适用于已转换的nii文件等场景)
# false: 保持目录路径不变 (适用于dcm2nii等需要整个文件夹的任务)
# 对于dcm2nii任务，必须设置为false
auto_select_first_file: false

# Preprocessing settings
Preprocessing:
  dcm2nii:
    images: [T1, T2, DWI, ADC]
    dcm2niix_path: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\software\dcm2nii\dcm2niix.exe
    compress: true
    anonymize: false
    merge_slices: "2"  # "y"=default, "2"=by series, "n"=no merge
    single_file_mode: null  # null=don't specify (recommended for 3D)
    
  # n4_correction:
  #   images: [pre_contrast, LAP, PVP, delay_3min]
  #   num_fitting_levels: 2

  # resample:
  #   images: [pre_contrast, LAP, PVP, delay_3min]
  #   target_spacing: [3.0, 3.0, 3.0]  # Target voxel spacing in x, y, z

  # # Z-Score标准化 - 将图像强度标准化为均值0、标准差1的分布
  # zscore_normalization:
  #   images: [pre_contrast, LAP, PVP, delay_3min]  # 要处理的图像序列
  #   only_inmask: false  # 是否仅在掩码内计算统计量
  #   # mask_key: mask  # 当only_inmask为true时使用的掩码名称

  # # 直方图标准化 - 简化版  FIXME 调试版本
  # # histogram_standardization:
  # #   images: [pre_contrast, LAP, delay_3min]  # 要处理的图像序列
  # #   reference_key: PVP  # 参考图像的键名

  # registration:
  #   images: [pre_contrast, LAP, PVP, delay_3min]
  #   fixed_image: PVP
  #   moving_images: [pre_contrast, LAP, delay_3min]
  #   type_of_transform: SyNRA  # support all ants registration methods
  #   use_mask: false

# General settings
processes: 1  # Number of parallel processes
random_state: 42  # Random seed for reproducibility
