images:
  subj003:
    AxT1FLAIR: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\AxT1FLAIR
    AxT2FRFSE: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\AxT2FRFSE
    AxT2fsFLAIR: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\AxT2fsFLAIR
    SagT2FRFSE: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\SagT2FRFSE

  subj004:
    AxT1FLAIR: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\AxT1FLAIR
    AxT2FRFSE: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\AxT2FRFSE
    AxT2fsFLAIR: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\AxT2fsFLAIR
    SagT2FRFSE: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\SagT2FRFSE


