images:
  subj003:
    T1: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\AxT1FLAIR
    T2: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\AxT2FRFSE
    DWI: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\AxT2fsFLAIR
    ADC: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj003\SagT2FRFSE

  subj004:
    T1: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\AxT1FLAIR
    T2: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\AxT2FRFSE
    DWI: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\AxT2fsFLAIR
    ADC: F:\work\workstation_b\dingHuYingXiang\the_4_training_202504\demo_data\datasets_dcm\images\subj004\SagT2FRFSE
