# PyRadiomics Configuration File
# This file contains settings for extracting radiomics features from medical images.
# It defines which features to extract and how to process the images before feature extraction.
#
# This configuration is set up for analyzing MR data with small (~3mm) slice thickness.
# These settings can be used as a starting point but may need optimization for specific datasets.

# When using these settings for analysis, add the PyRadiomics version used:
# #############################  Extracted using PyRadiomics version: <version>  ######################################

# Image Types Configuration
# Defines the image preprocessing filters to apply before feature extraction

imageType: 
  Original: {}                       # Extract features from the original image without filtering
  # LoG:                            # Laplacian of Gaussian filter - enhances edges in images
    # If using sigma values >5, increase padDistance. With resampling to (2, 2, 2), 
    # sigma values < 2 mm are not recommended.
    # sigma: [2.0, 3.0, 4.0, 5.0, 6.0]  # Sigma values control the scale of the filter (larger = more smoothing)
  # Wavelet: {}                     # Wavelet decomposition - captures frequency information at different scales
  # Square: {}                      # Square filter - enhances intensity differences
  # SquareRoot: {}                  # Square root filter - reduces intensity differences
  # Logarithm: {}                   # Logarithm filter - enhances low intensity details
  # Exponential: {}                 # Exponential filter - enhances high intensity details
  # Gradient: {}                    # Gradient filter - enhances edges and boundaries
  # LBP3D: {}                       # Local Binary Pattern features - captures texture patterns

# Feature Classes Configuration
# Defines which feature classes to extract
featureClass:
  # Note: redundant features (Compactness 1, Compactness 2, Spherical Disproportion) are disabled by default
  # They can be enabled by specifying individual feature names
  shape:                            # Shape features - describe 3D geometric properties of the ROI
  firstorder:                       # First order statistics - describe intensity distribution (histogram-based)
  glcm:                             # Gray Level Co-occurrence Matrix - texture features describing local intensity arrangements
  glrlm:                            # Gray Level Run Length Matrix - texture features describing run lengths of similar intensities
  glszm:                            # Gray Level Size Zone Matrix - texture features describing sizes of similar intensity zones
  ngtdm:                            # Neighboring Gray Tone Difference Matrix - texture features describing intensity differences between neighboring voxels
  gldm:                             # Gray Level Dependence Matrix - texture features describing dependencies between gray levels

# General Settings
setting:
  # Normalization Settings
  # MR signal is usually relative, with large differences between scanners and vendors.
  # Normalization can reduce these confounding effects.
  normalize: true                   # Whether to normalize intensities before feature calculation
  # normalize: false                # Set to false for absolute value images (e.g., ADC maps, T2 maps)
  normalizeScale: 100               # Scale factor for normalization - allows using consistent bin widths

  # Resampling Settings
  # For thin slices (~1mm) or isotropic volumes, resampledPixelSpacing may be reduced to (1, 1, 1)
  # For isotropic volumes, consider disabling resampling entirely
  # Note: Increasing spacing examines more coarse textures, which may improve feature stability
#  interpolator: 'sitkBSpline'       # Interpolation algorithm used during resampling
#  resampledPixelSpacing: [2, 2, 2]  # Target voxel size in mm for resampling

  # Mask Validation Settings
  # correctMask and geometryTolerance are not needed when both image and mask are resampled
  # For very small masks, consider enabling size constraints:
  #minimumROIDimensions: 2           # Minimum size in number of voxels along each dimension
  #minimumROISize: 50                # Minimum total number of voxels in ROI

  # Image Discretization Settings
  # The ideal number of bins is typically between 16-128
  binWidth: 25                    # Fixed bin width for discretization - best for comparing across datasets
  # binCount: 32                      # Fixed number of bins - alternative to binWidth

  # First Order Specific Settings
  # When normalizing, gray values below the mean will be negative
  # Shifting by 300 (3 StdDevs * 100) ensures most voxels are positive
  voxelArrayShift: 300              # Value to add to gray levels after normalization

  # Miscellaneous Settings
  # Default label value for segmentation masks
  # Labels can also be specified via command line, function call, or CSV column
  # label: 1                        # Value in the mask that identifies the ROI