# Copyright (c) 2024-2026 Li Chao, Dong Mengshi and HABIT Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""L3 domain layer: the eight protocols and their built-in implementations.

Importing this package registers every built-in component in its domain
registry, so ``<Registry>.available()`` and ``list_plugins(domain=...)``
reflect the full built-in surface after a single import. Heavy third-party
libraries (scikit-learn, scikit-image) are imported lazily inside method
bodies, keeping this package cheap to import.
"""

from __future__ import annotations

from habit.domain.protocols import (
    CohortFeaturePreprocessor,
    Combiner,
    HabitatAssigner,
    HabitatFeatureExtractor,
    HabitatModelFitter,
    ImagePerturbation,
    PoolingMarker,
    Preprocessor,
    Seedable,
    SubjectFeaturePreprocessor,
    SupervoxelFeatureExtractor,
    Supervoxelizer,
    VoxelFeatureExtractor,
)
from habit.domain.table_protocols import (
    Classifier,
    FeatureSelector,
    Metric,
    TablePreprocessor,
)
from habit.domain.pipeline import SubjectPipeline, TablePipeline
from habit.domain.pooling import PooledUnits, fan_in
from habit.domain.pooling_marker import PoolMarker, PoolMarkerParams, PoolingRegistry
from habit.domain.stages import (
    ResolvedStage,
    design_from_stages,
    execute_habitat_dataflow,
    resolve_habitat_stages,
    run_subject_stage_prefix,
)
from habit.domain.postprocess import (
    ConnectedComponentPostprocess,
    build_connected_component_postprocess,
)
from habit.domain.voxel_features import (
    RawVoxelFeatures,
    RawVoxelFeaturesParams,
    VoxelFeatureExtractorRegistry,
    extract_voxel_texture,
)
from habit.domain.supervoxel import (
    GmmSupervoxelizer,
    GmmSupervoxelizerParams,
    KMeansSupervoxelizer,
    KMeansSupervoxelizerParams,
    SlicSupervoxelizer,
    SlicSupervoxelizerParams,
    SupervoxelizerRegistry,
)
from habit.domain.supervoxel_features import (
    MeanSupervoxelFeatures,
    MeanSupervoxelFeaturesParams,
    MeanVoxelFeatures,
    MeanVoxelFeaturesParams,
    PercentileSupervoxelFeatures,
    PercentileSupervoxelFeaturesParams,
    StdSupervoxelFeatures,
    StdSupervoxelFeaturesParams,
    SupervoxelFeatureExtractorRegistry,
    SupervoxelRadiomicsFeatures,
    SupervoxelRadiomicsFeaturesParams,
)
from habit.domain.combiners import (
    AverageCombiner,
    AverageCombinerParams,
    CombinerRegistry,
    ConcatCombiner,
    ConcatCombinerParams,
    DifferenceCombiner,
    DifferenceCombinerParams,
    ExpressionCombiner,
    ExpressionCombinerParams,
    KineticCombiner,
    KineticCombinerParams,
    RatioCombiner,
    RatioCombinerParams,
    WeightedConcatCombiner,
    WeightedConcatCombinerParams,
)
from habit.domain.trees import (
    HabitatFeatureTree,
    SupervoxelFeatureTree,
    VoxelFeatureTree,
    build_habitat_extractor,
    build_supervoxel_extractor,
    build_voxel_extractor,
)
from habit.domain.feature_preprocessing import (
    Binning,
    BinningParams,
    CohortPreprocessingChain,
    CorrelationFilter,
    CorrelationFilterParams,
    PreciseCorrelationFilter,
    PreciseCorrelationFilterParams,
    FeaturePreprocessingMethodRegistry,
    FeatureWhitelist,
    FeatureWhitelistParams,
    Impute,
    ImputeParams,
    LogTransform,
    LogTransformParams,
    MinMaxScaling,
    MinMaxScalingParams,
    RobustScaling,
    RobustScalingParams,
    SubjectPreprocessingChain,
    VarianceFilter,
    VarianceFilterParams,
    Winsorizing,
    WinsorizingParams,
    ZScoreScaling,
    ZScoreScalingParams,
    build_methods,
)
from habit.domain.habitat_model import (
    GmmHabitatModelFitter,
    GmmHabitatModelFitterParams,
    HabitatModelFitterRegistry,
    KMeansHabitatModelFitter,
    KMeansHabitatModelFitterParams,
)
from habit.domain.assignment import (
    HabitatAssignerRegistry,
    NearestCentroidAssigner,
    NearestCentroidAssignerParams,
)
from habit.domain.habitat_features import (
    EachHabitatRadiomicsFeatures,
    EachHabitatRadiomicsFeaturesParams,
    HabitatFeatureComparison,
    HabitatFeaturePanel,
    compare_habitat_features,
    to_habitat_feature_panel,
    GraphHabitatFeatures,
    GraphHabitatFeaturesParams,
    HabitatFeatureExtractorRegistry,
    HabitatVolumeFeatures,
    HabitatVolumeFeaturesParams,
    IthHabitatFeatures,
    IthHabitatFeaturesParams,
    MsiHabitatFeatures,
    MsiHabitatFeaturesParams,
    NonRadiomicsHabitatFeatures,
    NonRadiomicsHabitatFeaturesParams,
    TraditionalRadiomicsHabitatFeatures,
    TraditionalRadiomicsHabitatFeaturesParams,
    WholeHabitatRadiomicsFeatures,
    WholeHabitatRadiomicsFeaturesParams,
)
from habit.domain.table_preprocessing import (
    BinningPreprocessor,
    BinningPreprocessorParams,
    CorrelationFilterPreprocessor,
    CorrelationFilterPreprocessorParams,
    PreciseCorrelationFilterPreprocessor,
    PreciseCorrelationFilterPreprocessorParams,
    LogPreprocessor,
    LogPreprocessorParams,
    MinMaxPreprocessor,
    MinMaxPreprocessorParams,
    RobustPreprocessor,
    RobustPreprocessorParams,
    TablePreprocessorRegistry,
    VarianceFilterPreprocessor,
    VarianceFilterPreprocessorParams,
    WinsorizePreprocessor,
    WinsorizePreprocessorParams,
    ZScorePreprocessor,
    ZScorePreprocessorParams,
)
from habit.domain.feature_selection import (
    AnovaSelector,
    AnovaSelectorParams,
    Chi2Selector,
    Chi2SelectorParams,
    CorrelationSelector,
    CorrelationSelectorParams,
    FeatureSelectorRegistry,
    IccSelector,
    IccSelectorParams,
    LassoSelector,
    LassoSelectorParams,
    MrmrSelector,
    MrmrSelectorParams,
    RfecvSelector,
    RfecvSelectorParams,
    StatisticalTestSelector,
    StatisticalTestSelectorParams,
    StepwiseSelector,
    StepwiseSelectorParams,
    UnivariateLogisticSelector,
    UnivariateLogisticSelectorParams,
    VarianceSelector,
    VarianceSelectorParams,
    VifSelector,
    VifSelectorParams,
)
from habit.domain.classification import (
    AdaboostClassifier,
    AdaboostClassifierParams,
    AutogluonTabularClassifier,
    AutogluonTabularClassifierParams,
    BernoulliNbClassifier,
    BernoulliNbClassifierParams,
    ClassifierRegistry,
    DecisionTreeClassifier,
    DecisionTreeClassifierParams,
    GaussianNbClassifier,
    GaussianNbClassifierParams,
    GradientBoostingClassifier,
    GradientBoostingClassifierParams,
    KnnClassifier,
    KnnClassifierParams,
    LogisticRegressionClassifier,
    LogisticRegressionClassifierParams,
    MlpClassifier,
    MlpClassifierParams,
    MultinomialNbClassifier,
    MultinomialNbClassifierParams,
    RandomForestClassifier,
    RandomForestClassifierParams,
    SvcClassifier,
    SvcClassifierParams,
    SvmClassifier,
    SvmClassifierParams,
    XgboostClassifier,
    XgboostClassifierParams,
)
from habit.domain.evaluation import (
    AccuracyMetric,
    AccuracyMetricParams,
    AucConfidenceInterval,
    AucMetric,
    AucMetricParams,
    CalibrationResult,
    DelongResult,
    F1ScoreMetric,
    F1ScoreMetricParams,
    HosmerLemeshowPValueMetric,
    HosmerLemeshowPValueMetricParams,
    MetricRegistry,
    NpvMetric,
    NpvMetricParams,
    PpvMetric,
    PpvMetricParams,
    SensitivityMetric,
    SensitivityMetricParams,
    SpecificityMetric,
    SpecificityMetricParams,
    SpiegelhalterZPValueMetric,
    SpiegelhalterZPValueMetricParams,
    auc_confidence_interval,
    calibration_tests,
    delong_test,
    icc_analysis,
    repeat_measurement_matrix,
)
from habit.domain.image_preprocessing import (
    AdaptiveHistogramEqualization,
    HistogramStandardization,
    N4Correction,
    PreprocessorRegistry,
    Registration,
    Reorientation,
    Resample,
    ZScoreNormalization,
)
from habit.domain.precision import (
    BSplineDeformPerturbation,
    BSplineDeformPerturbationParams,
    GaussianNoisePerturbation,
    GaussianNoisePerturbationParams,
    GradientWeightedPerturbation,
    GradientWeightedPerturbationParams,
    ImagePerturbationRegistry,
    MorphologicalPerturbation,
    MorphologicalPerturbationParams,
    PerturbationChain,
    PreciseFeatureSet,
    RigidPerturbation,
    RigidPerturbationParams,
    RotationPerturbation,
    RotationPerturbationParams,
    SliceExtentPerturbation,
    SliceExtentPerturbationParams,
    TranslationPerturbation,
    TranslationPerturbationParams,
    aggregate_panels,
    align_habitat_map,
    habitat_stability,
    identify_precise_features,
    perturb_image,
    precision_panel,
    prior2024_retest_perturbation,
)

__all__ = [
    # The eight domain protocols plus the seeding contract.
    "VoxelFeatureExtractor",
    "SubjectFeaturePreprocessor",
    "CohortFeaturePreprocessor",
    "Supervoxelizer",
    "SupervoxelFeatureExtractor",
    "HabitatModelFitter",
    "HabitatAssigner",
    "HabitatFeatureExtractor",
    "ImagePerturbation",
    "Preprocessor",
    "Seedable",
    # Feature block combiners: the internal nodes of composition trees.
    "Combiner",
    "CombinerRegistry",
    "ConcatCombiner",
    "ConcatCombinerParams",
    "WeightedConcatCombiner",
    "WeightedConcatCombinerParams",
    "AverageCombiner",
    "AverageCombinerParams",
    "RatioCombiner",
    "RatioCombinerParams",
    "DifferenceCombiner",
    "DifferenceCombinerParams",
    "KineticCombiner",
    "KineticCombinerParams",
    "ExpressionCombiner",
    "ExpressionCombinerParams",
    # Composition trees: wrappers evaluating nested feature specs.
    "VoxelFeatureTree",
    "SupervoxelFeatureTree",
    "HabitatFeatureTree",
    "build_voxel_extractor",
    "build_supervoxel_extractor",
    "build_habitat_extractor",
    # The four table-ML protocols.
    "TablePreprocessor",
    "FeatureSelector",
    "Classifier",
    "Metric",
    # Composition.
    "SubjectPipeline",
    "TablePipeline",
    # Cross-subject pooling atoms of the habitat dataflow.
    "PooledUnits",
    "fan_in",
    "PoolMarker",
    "PoolMarkerParams",
    "PoolingRegistry",
    # Stage dataflow (ordered named stages + shared executor).
    "ResolvedStage",
    "design_from_stages",
    "execute_habitat_dataflow",
    "resolve_habitat_stages",
    "run_subject_stage_prefix",
    "PoolingMarker",
    # Label-map post-processing (not a registry protocol).
    "ConnectedComponentPostprocess",
    "build_connected_component_postprocess",
    # Built-in voxel feature extractors.
    "RawVoxelFeatures",
    "RawVoxelFeaturesParams",
    "VoxelFeatureExtractorRegistry",
    "extract_voxel_texture",
    # Built-in supervoxelizers.
    "SlicSupervoxelizer",
    "SlicSupervoxelizerParams",
    "KMeansSupervoxelizer",
    "KMeansSupervoxelizerParams",
    "GmmSupervoxelizer",
    "GmmSupervoxelizerParams",
    "SupervoxelizerRegistry",
    # Built-in supervoxel feature extractors.
    "MeanVoxelFeatures",
    "MeanVoxelFeaturesParams",
    "MeanSupervoxelFeatures",
    "MeanSupervoxelFeaturesParams",
    "StdSupervoxelFeatures",
    "StdSupervoxelFeaturesParams",
    "PercentileSupervoxelFeatures",
    "PercentileSupervoxelFeaturesParams",
    "SupervoxelRadiomicsFeatures",
    "SupervoxelRadiomicsFeaturesParams",
    "SupervoxelFeatureExtractorRegistry",
    # Feature preprocessing: two chains over eight shared methods.
    "SubjectPreprocessingChain",
    "CohortPreprocessingChain",
    "build_methods",
    "FeaturePreprocessingMethodRegistry",
    "Impute",
    "ImputeParams",
    "MinMaxScaling",
    "MinMaxScalingParams",
    "ZScoreScaling",
    "ZScoreScalingParams",
    "RobustScaling",
    "RobustScalingParams",
    "LogTransform",
    "LogTransformParams",
    "Winsorizing",
    "WinsorizingParams",
    "Binning",
    "BinningParams",
    "VarianceFilter",
    "VarianceFilterParams",
    "CorrelationFilter",
    "CorrelationFilterParams",
    "PreciseCorrelationFilter",
    "PreciseCorrelationFilterParams",
    "FeatureWhitelist",
    "FeatureWhitelistParams",
    # Built-in habitat model fitters.
    "KMeansHabitatModelFitter",
    "KMeansHabitatModelFitterParams",
    "GmmHabitatModelFitter",
    "GmmHabitatModelFitterParams",
    "HabitatModelFitterRegistry",
    # Built-in habitat assigners.
    "NearestCentroidAssigner",
    "NearestCentroidAssignerParams",
    "HabitatAssignerRegistry",
    # Built-in habitat feature extractors.
    "MsiHabitatFeatures",
    "MsiHabitatFeaturesParams",
    "GraphHabitatFeatures",
    "GraphHabitatFeaturesParams",
    "IthHabitatFeatures",
    "IthHabitatFeaturesParams",
    "HabitatVolumeFeatures",
    "HabitatVolumeFeaturesParams",
    "NonRadiomicsHabitatFeatures",
    "NonRadiomicsHabitatFeaturesParams",
    "TraditionalRadiomicsHabitatFeatures",
    "TraditionalRadiomicsHabitatFeaturesParams",
    "WholeHabitatRadiomicsFeatures",
    "WholeHabitatRadiomicsFeaturesParams",
    "EachHabitatRadiomicsFeatures",
    "EachHabitatRadiomicsFeaturesParams",
    "HabitatFeaturePanel",
    "HabitatFeatureComparison",
    "to_habitat_feature_panel",
    "compare_habitat_features",
    "HabitatFeatureExtractorRegistry",
    # Built-in table preprocessors.
    "TablePreprocessorRegistry",
    "MinMaxPreprocessor",
    "MinMaxPreprocessorParams",
    "ZScorePreprocessor",
    "ZScorePreprocessorParams",
    "RobustPreprocessor",
    "RobustPreprocessorParams",
    "BinningPreprocessor",
    "BinningPreprocessorParams",
    "WinsorizePreprocessor",
    "WinsorizePreprocessorParams",
    "LogPreprocessor",
    "LogPreprocessorParams",
    "VarianceFilterPreprocessor",
    "VarianceFilterPreprocessorParams",
    "CorrelationFilterPreprocessor",
    "CorrelationFilterPreprocessorParams",
    "PreciseCorrelationFilterPreprocessor",
    "PreciseCorrelationFilterPreprocessorParams",
    # Built-in feature selectors.
    "FeatureSelectorRegistry",
    "VarianceSelector",
    "VarianceSelectorParams",
    "CorrelationSelector",
    "CorrelationSelectorParams",
    "VifSelector",
    "VifSelectorParams",
    "AnovaSelector",
    "AnovaSelectorParams",
    "Chi2Selector",
    "Chi2SelectorParams",
    "StatisticalTestSelector",
    "StatisticalTestSelectorParams",
    "UnivariateLogisticSelector",
    "UnivariateLogisticSelectorParams",
    "StepwiseSelector",
    "StepwiseSelectorParams",
    "RfecvSelector",
    "RfecvSelectorParams",
    "LassoSelector",
    "LassoSelectorParams",
    "IccSelector",
    "IccSelectorParams",
    "MrmrSelector",
    "MrmrSelectorParams",
    # Built-in classifiers.
    "ClassifierRegistry",
    "DecisionTreeClassifier",
    "DecisionTreeClassifierParams",
    "KnnClassifier",
    "KnnClassifierParams",
    "SvmClassifier",
    "SvmClassifierParams",
    "SvcClassifier",
    "SvcClassifierParams",
    "MlpClassifier",
    "MlpClassifierParams",
    "LogisticRegressionClassifier",
    "LogisticRegressionClassifierParams",
    "RandomForestClassifier",
    "RandomForestClassifierParams",
    "GradientBoostingClassifier",
    "GradientBoostingClassifierParams",
    "XgboostClassifier",
    "XgboostClassifierParams",
    "AdaboostClassifier",
    "AdaboostClassifierParams",
    "GaussianNbClassifier",
    "GaussianNbClassifierParams",
    "MultinomialNbClassifier",
    "MultinomialNbClassifierParams",
    "BernoulliNbClassifier",
    "BernoulliNbClassifierParams",
    "AutogluonTabularClassifier",
    "AutogluonTabularClassifierParams",
    # Built-in evaluation metrics and statistics wrappers.
    "MetricRegistry",
    "AccuracyMetric",
    "AccuracyMetricParams",
    "SensitivityMetric",
    "SensitivityMetricParams",
    "SpecificityMetric",
    "SpecificityMetricParams",
    "PpvMetric",
    "PpvMetricParams",
    "NpvMetric",
    "NpvMetricParams",
    "F1ScoreMetric",
    "F1ScoreMetricParams",
    "AucMetric",
    "AucMetricParams",
    "HosmerLemeshowPValueMetric",
    "HosmerLemeshowPValueMetricParams",
    "SpiegelhalterZPValueMetric",
    "SpiegelhalterZPValueMetricParams",
    "DelongResult",
    "delong_test",
    "AucConfidenceInterval",
    "auc_confidence_interval",
    "CalibrationResult",
    "calibration_tests",
    "repeat_measurement_matrix",
    "icc_analysis",
    # Precision analysis (simulated test-retest and the precise-feature screen).
    "ImagePerturbationRegistry",
    "PreprocessorRegistry",
    "ZScoreNormalization",
    "Resample",
    "Reorientation",
    "N4Correction",
    "HistogramStandardization",
    "AdaptiveHistogramEqualization",
    "Registration",
    "BSplineDeformPerturbation",
    "BSplineDeformPerturbationParams",
    "GaussianNoisePerturbation",
    "GaussianNoisePerturbationParams",
    "GradientWeightedPerturbation",
    "GradientWeightedPerturbationParams",
    "MorphologicalPerturbation",
    "MorphologicalPerturbationParams",
    "SliceExtentPerturbation",
    "SliceExtentPerturbationParams",
    "TranslationPerturbation",
    "TranslationPerturbationParams",
    "RotationPerturbation",
    "RotationPerturbationParams",
    "RigidPerturbation",
    "RigidPerturbationParams",
    "PerturbationChain",
    "PreciseFeatureSet",
    "precision_panel",
    "aggregate_panels",
    "identify_precise_features",
    "perturb_image",
    "align_habitat_map",
    "habitat_stability",
    "prior2024_retest_perturbation",
]
