run_mode: predict
pipeline_path: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/ml_clinical/outputs/models/LogisticRegression_final_pipeline.pkl
input:
- path: /mnt/f/work/habit_project_v1/demo_data/ml_data/clinical_feature.csv
  name: clinical_
  subject_id_col: subjID
  label_col: label
output: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/ml_clinical/outputs/predictions_cli
evaluate: true
output_label_col: predicted_label
output_prob_col: predicted_probability
