paths:
  params_file: /mnt/f/work/habit_project_v1/config/radiomics/parameter.yaml
  images_folder: /mnt/f/work/habit_project_v1/.cursor/test/resample_02
  out_dir: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/radiomics_resample02/outputs
processing:
  n_processes: 2
  save_every_n_files: 5
  process_image_types:
  - T1
  - T2
export:
  export_by_image_type: true
  export_combined: true
  export_format: csv
  add_timestamp: false
logging:
  level: INFO
  console_output: true
  file_output: true
