"""
Sphinx configuration file for HABIT project documentation.

This file configures Sphinx to generate documentation from source code
and existing Markdown files.
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Add project root to Python path for autodoc
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# -- Project information -----------------------------------------------------

project = 'HABIT'
copyright = f'{datetime.now().year}, HABIT Team'
author = 'HABIT Team'

# The full version, including alpha/beta/rc tags
try:
    from habit import __version__
    release = __version__
    version = '.'.join(__version__.split('.')[:2])  # Major.Minor
except ImportError:
    release = '0.1.0'
    version = '0.1'

# -- General configuration ----------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',           # Automatically generate API docs from docstrings
    'sphinx.ext.autosummary',       # Generate summary tables
    'sphinx.ext.viewcode',          # Add source code links
    'sphinx.ext.napoleon',          # Support Google/NumPy style docstrings
    'sphinx.ext.intersphinx',       # Link to external documentation
    'sphinx.ext.mathjax',           # Render math equations
    'sphinx.ext.githubpages',       # Support GitHub Pages
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '**.ipynb_checkpoints',
]

# The suffix(es) of source filenames
if ENABLE_MARKDOWN:
    source_suffix = {
        '.rst': 'restructuredtext',
        '.md': 'myst',
    }
else:
    source_suffix = {
        '.rst': 'restructuredtext',
    }

# -- Options for HTML output --------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# Custom sidebar templates
html_sidebars = {
    '**': [
        'versions.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# -- Extension configuration -------------------------------------------------

# -- Options for autodoc extension --------------------------------------------

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Mock imports for dependencies that may be difficult to install
autodoc_mock_imports = [
    'antspyx',
    'SimpleITK',
    'pyradiomics',
]

# -- Options for napoleon extension -------------------------------------------

# Support both Google and NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# -- Options for intersphinx extension ----------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'sklearn': ('https://scikit-learn.org/stable/', None),
    'click': ('https://click.palletsprojects.com/', None),
}

# -- Options for MyST Parser --------------------------------------------------

if ENABLE_MARKDOWN:
    myst_enable_extensions = [
        'colon_fence',
        'deflist',
        'dollarmath',
        'html_admonition',
        'html_image',
        'linkify',
        'replacements',
        'smartquotes',
        'substitution',
        'tasklist',
    ]

# -- Options for autosummary extension ----------------------------------------

autosummary_generate = True

# -- Custom configuration ----------------------------------------------------

# HTML title
html_title = f'{project} {version} Documentation'

# HTML logo (if available)
# html_logo = '_static/logo.png'

# HTML favicon (if available)
# html_favicon = '_static/favicon.ico'
