run_mode: predict
pipeline_path: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/habitat_two_step_voxel_radiomics/outputs/habitat_pipeline.pkl
data_dir: /mnt/f/work/habit_project_v1/demo_data/preprocessed/processed_images
out_dir: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/habitat_two_step_voxel_radiomics_predict/outputs
FeatureConstruction:
  voxel_level:
    method: concat(voxel_radiomics(delay3, params_file, kernelRadius))
    params:
      params_file: /mnt/f/work/habit_project_v1/config/radiomics/params_voxel_radiomics.yaml
      kernelRadius: 3
      voxelBatch: 1000
      useTorchRadiomics: auto
  supervoxel_level:
    supervoxel_file_keyword: '*_supervoxel.nrrd'
    method: mean_voxel_features()
    params:
      params_file: /mnt/f/work/habit_project_v1/config/radiomics/params_supervoxel_radiomics.yaml
      supervoxelUnionBboxCrop: true
      useSupervoxelCext: auto
  preprocessing_for_subject_level:
    methods:
    - method: winsorize
      winsor_limits:
      - 0.05
      - 0.05
      global_normalize: false
    - method: minmax
      global_normalize: false
  preprocessing_for_group_level:
    methods:
    - method: winsorize
      winsor_limits:
      - 0.05
      - 0.05
      global_normalize: false
    - method: variance_filter
      variance_threshold: 0.01
      global_normalize: false
    - method: correlation_filter
      corr_threshold: 0.9
      corr_method: spearman
      global_normalize: false
    - method: minmax
      global_normalize: false
HabitatSegmentation:
  clustering_mode: two_step
  supervoxel:
    algorithm: kmeans
    n_clusters: 50
    max_iter: 300
    n_init: 10
    one_step_settings:
      min_clusters: 2
      max_clusters: 10
      fixed_n_clusters: null
      selection_method: elbow
      plot_validation_curves: true
  habitat:
    algorithm: kmeans
    max_clusters: 10
    habitat_cluster_selection_method:
    - elbow
    fixed_n_clusters: null
    max_iter: 300
    n_init: 10
processes: 2
cap_processes_to_gpu_pool: false
individual_subject_timeout_sec: 900
oom_backoff: false
resume: true
strict_checkpoint_hash: false
checkpoint_dir: null
force_rerun_subjects: []
retry_failed_subjects: false
individual_subject_auto_retry_rounds: 2
individual_subject_parallel_mode: persistent
persistent_worker_max_consecutive_failures: 1
persistent_worker_recycle_after_tasks: 0
clear_checkpoint_on_success: false
plot_curves: true
save_results_csv: true
random_state: 42
debug: false
