data_dir: /mnt/f/work/habit_project_v1/demo_data/preprocessed/processed_images
out_dir: /mnt/f/work/habit_project_v1/demo_data/results_config_test/cases/06_preprocess_demo/outputs
auto_select_first_file: true
Preprocessing:
  resample:
    images:
    - delay2
    - delay3
    - delay5
    target_spacing:
    - 3.0
    - 3.0
    - 3.0
    img_mode: bilinear
  registration:
    images:
    - delay2
    - delay3
    - delay5
    fixed_image: delay2
    use_mask: true
    backend: ants
    type_of_transform: Rigid
  zscore_normalization:
    images:
    - delay2
    - delay3
    - delay5
    only_inmask: false
    clip_values:
    - -3
    - 3
save_options:
  save_intermediate: true
  intermediate_steps: []
processes: 2
random_state: 42
